Put sound on sonic KC
digital-brilliance-hour/ogres-mayhem pull request #45
Opened 2022-05-25 21:36 UTC by Juiceman919

2022-05-25 21:46 UTC, JingoBurch commented
I had sound for everything but the run and walk animations for sonic.

2022-05-26 00:46 UTC, digitalbrilliancehour commented on build/Data/CHARS/Sonic/Sonic.txt
> +	sound	data/sounds/walk.wav
sound fx should be on frames 3 and 6

2022-05-26 00:47 UTC, digitalbrilliancehour commented on build/Data/CHARS/Sonic/Sonic.txt
> +	sound	data/sounds/walk.wav
sound fx should be on frames 4 and 6

2022-05-26 00:47 UTC, digitalbrilliancehour requested changes
Check out my comments on the sound fx

2022-05-30 22:30 UTC, digitalbrilliancehour approved these changes

2022-05-30 22:30 UTC, merged